### ISSUE TITLE
jekyll 对 mermaid 的支持

### ISSUE THREAD

**Issue by Ran-Xing** [wechaty/jekyll#102]
###  Demo

```mermaid
flowchart LR
    Polyglot-->Python
    Polyglot-->Go
    Polyglot -->Rust
    Python-->Grpc
    Go-->Grpc
    Rust-->Grpc
    Grpc-->Puppet
    Puppet-->Padlocal
    Puppet-->Wechat4U
    Puppet-->XP
    Padlocal-->微信
    Wechat4U-->微信
    XP-->微信
```
mermaid 常用于流程图的制作

大多数的 markdown 软件都支持 mermaid 

jekyll 需要导入js才能支持 mermaid 

希望能为jekyll启用这一强大的工具

**Comment by huan** [comment]
Yes, thank you for asking for that!

We have already plan adding support for the mermaid, see:

- https://github.com/wechaty/docusaurus/issues/1486

I would love to accept a PR for it.

**Comment by XRSec** [comment]
好像并没有生效 [Github](https://wechaty.js.org/2022/04/13/wechaty-gateway-use/)

**Comment by huan** [comment]
Yes, it has not been implemented/added yet.

It would be great if you can submit a PR to support this great feature.
